# Generated by Django 4.2.27 on 2025-12-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='About',
        ),
    ]
